### ISSUE TITLE
How can I Customize size? ❓ 

### ISSUE THREAD

**Issue by joseph-sx** [akamfoad/qrcode#25]
as the tittle says, how can i customize the size of the resulted svg ?

thanks in advance.

**Comment by akamfoad** [comment]
Hi @joseph-sx 

Just sent a new version `0.3.2` in which I added height and width option properties to QRCodeSVG

Check [this demo](https://stackblitz.com/edit/vitejs-vite-auq9ya?file=src%2Fmain.ts) for more info

**Comment by joseph-sx** [comment]
Thanks! We'll check it out
